name: "CARTO PR Analysis"
description: "Analyzes PRs merged to carto/main to identify CARTO-modified files"

inputs:
  github_token:
    description: "GitHub token with org:read and repo permissions"
    required: true
  output_path:
    description: "Directory to write analysis files"
    required: false
    default: "/tmp/carto-analysis"

outputs:
  carto_files_path:
    description: "Path to file containing CARTO-modified file list"
    value: ${{ steps.analyze.outputs.carto_files_path }}
  carto_prs_path:
    description: "Path to file containing CARTO PR data (JSON)"
    value: ${{ steps.analyze.outputs.carto_prs_path }}
  file_count:
    description: "Number of CARTO-modified files"
    value: ${{ steps.analyze.outputs.file_count }}
  pr_count:
    description: "Number of CARTO PRs analyzed"
    value: ${{ steps.analyze.outputs.pr_count }}

runs:
  using: "composite"
  steps:
    - name: Check if analysis already exists
      id: check-existing
      shell: bash
      run: |
        OUTPUT_PATH="${{ inputs.output_path }}"
        if [ -f "${OUTPUT_PATH}/carto_files.txt" ] && [ -f "${OUTPUT_PATH}/carto_prs.json" ]; then
          FILE_COUNT=$(wc -l < "${OUTPUT_PATH}/carto_files.txt" | tr -d ' ')
          echo "[CARTO Analysis] Using existing analysis (${FILE_COUNT} files)"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "[CARTO Analysis] No existing analysis found, generating..."
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Fetch CartoDB org members
      id: org-members
      if: steps.check-existing.outputs.exists != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "::group::Fetching CartoDB org members"

        ORG_MEMBERS=$(gh api "orgs/CartoDB/members" --paginate --jq '.[].login' 2>/dev/null | tr '\n' '|' | sed 's/|$//')

        if [ -z "$ORG_MEMBERS" ]; then
          echo "[CARTO Analysis] Warning: Could not fetch org members, using fallback"
          ORG_MEMBERS="Cartofante|mateo-di"
        fi

        MEMBER_COUNT=$(echo "$ORG_MEMBERS" | tr '|' '\n' | wc -l | tr -d ' ')
        echo "[CARTO Analysis] Found ${MEMBER_COUNT} org members"

        echo "pattern=${ORG_MEMBERS}" >> $GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Analyze CARTO PRs
      id: analyze
      if: steps.check-existing.outputs.exists != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ORG_PATTERN: ${{ steps.org-members.outputs.pattern }}
        OUTPUT_PATH: ${{ inputs.output_path }}
      run: |
        echo "::group::Analyzing CARTO PRs"

        mkdir -p "${OUTPUT_PATH}"

        # Fetch all merged PRs to carto/main with file lists
        echo "[CARTO Analysis] Fetching PRs merged to carto/main..."
        gh pr list \
          --repo ${{ github.repository }} \
          --base carto/main \
          --state merged \
          --limit 1000 \
          --json number,title,author,body,mergedAt,additions,deletions,files \
          > "${OUTPUT_PATH}/all_prs.json" 2>/dev/null || echo "[]" > "${OUTPUT_PATH}/all_prs.json"

        TOTAL_PRS=$(jq 'length' "${OUTPUT_PATH}/all_prs.json")
        echo "[CARTO Analysis] Found ${TOTAL_PRS} total PRs merged to carto/main"

        # Filter to CARTO org member authors only
        # This excludes upstream sync PRs (bot-authored) and external contributors
        jq --arg pattern "$ORG_PATTERN" '
          [.[] | select(.author.login | test("^(" + $pattern + ")$"; "i"))]
        ' "${OUTPUT_PATH}/all_prs.json" > "${OUTPUT_PATH}/carto_prs.json"

        CARTO_PRS=$(jq 'length' "${OUTPUT_PATH}/carto_prs.json")
        echo "[CARTO Analysis] Found ${CARTO_PRS} PRs by CARTO org members"

        # Extract unique file paths from CARTO PRs
        jq -r '[.[] | .files[].path] | unique | .[]' "${OUTPUT_PATH}/carto_prs.json" > "${OUTPUT_PATH}/carto_files.txt"

        FILE_COUNT=$(wc -l < "${OUTPUT_PATH}/carto_files.txt" | tr -d ' ')
        echo "[CARTO Analysis] Found ${FILE_COUNT} unique CARTO-modified files"

        # Cleanup temp file
        rm -f "${OUTPUT_PATH}/all_prs.json"

        # Output paths and counts
        echo "carto_files_path=${OUTPUT_PATH}/carto_files.txt" >> $GITHUB_OUTPUT
        echo "carto_prs_path=${OUTPUT_PATH}/carto_prs.json" >> $GITHUB_OUTPUT
        echo "file_count=${FILE_COUNT}" >> $GITHUB_OUTPUT
        echo "pr_count=${CARTO_PRS}" >> $GITHUB_OUTPUT

        echo "::endgroup::"

    - name: Use existing analysis
      id: use-existing
      if: steps.check-existing.outputs.exists == 'true'
      shell: bash
      env:
        OUTPUT_PATH: ${{ inputs.output_path }}
      run: |
        FILE_COUNT=$(wc -l < "${OUTPUT_PATH}/carto_files.txt" | tr -d ' ')
        PR_COUNT=$(jq 'length' "${OUTPUT_PATH}/carto_prs.json" 2>/dev/null || echo "0")

        echo "carto_files_path=${OUTPUT_PATH}/carto_files.txt" >> $GITHUB_OUTPUT
        echo "carto_prs_path=${OUTPUT_PATH}/carto_prs.json" >> $GITHUB_OUTPUT
        echo "file_count=${FILE_COUNT}" >> $GITHUB_OUTPUT
        echo "pr_count=${PR_COUNT}" >> $GITHUB_OUTPUT
